#!/bin/sh
# .githooks/pre-commit: bloquea commits directos en main o master
rama=$(git rev-parse --abbrev-ref HEAD)
if [ "$rama" = "main" ] || [ "$rama" = "master" ]; then
  echo "Prohibido hacer commits directos en $rama. Crea una rama: git switch -c funcionalidad/<nombre>"
  exit 1
fi
